<?php echo $this->breadcrumbs; ?>
<div class="row">
    <div class="col-sm-3">
        <?php echo $this->sidebar; ?>
    </div>
    <div class="col-sm-9">
        <h2 class="head__title">
            <?php echo $this->translate('My Designs'); ?>
        </h2>
        <div class="row">
            <div class="col-xs-12">
                <div class="m-b10 p-tb10">
                    <div class="row">
                        <div class="col-sm-6 col-md-9">
                            <p class="text-page p-t15 m-b0">
                                <?php echo $this->translate('Balance'); ?>:
                                <?php echo $this->currencySwitcher()->currencyFormat($this->balance); ?>
                            </p>
                        </div>
                        <div class="col-sm-6 col-md-3">
                            <?php //if($this->is_manual_mode): ?>
                                <a href="<?php echo $this->url('user_account_payments', ['action' => 'create-invoice']); ?>" class="btn__accept m-0">
                                    <?php echo $this->translate('Create Invoice');?>
                                </a>
                            <?php //endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?php if ($this->paginator->getCurrentItemCount()) : ?>
        <div class="catalog">
            <table class="order__table responsive__table m-t5 m-b40">
                <thead>
                <tr>
                    <th><?php echo $this->translate('Payment'); ?> #</th>
                    <th><?php echo $this->translate('Create'); ?></th>
                    <th><?php echo $this->translate('Amount'); ?></th>
                    <th><?php echo $this->translate('Message'); ?></th>
                    <th><?php echo $this->translate('Status'); ?></th>
                </tr>
                </thead>
                <tbody class="search-results">
                <?php echo $this->partial('user/payments/partials/list', ['paginator' => $this->paginator]); ?>
                </tbody>
            </table>
            <div class="loading__block col-xs-12 is-hidden">
                <i class="fa fa-spinner fa-pulse"></i>
            </div>
        </div>
        <ul class="pagination">
            <?php echo $this->paginationControl($this->paginator, 'Sliding', 'core/partials/paginator/paginator'); ?>
        </ul>
        <?php else: ?>
            <p class="title_text">
                <?php echo $this->translate('Payments not found.'); ?>
            </p>
        <?php endif; ?>
    </div>
</div>