<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <?php echo $this->form()->openTag($form); ?>
        <div class="sign__block">
            <h4 class="sign__block__title">
                <span><?php echo $this->translate('Complete Twitter registration'); ?></span>
            </h4>
            <div class="form-group <?php echo $form->get('email')->getMessages() ? 'has-error' : '';?>">
                <?php echo $this->formInput($form->get('email')->setAttributes([
                    'class' => 'form-control',
                    'placeholder' => 'Please enter your email address',
                ])); ?>
                <?php echo $this->formElementErrors()->render($form->get('email')); ?>
            </div>
            <?php echo $this->formSubmit($form
                ->get('submit')
                ->setAttributes([
                    'class' => 'sign__block__accept',
                    'value' => 'Save',
                ]));?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>
