<?php
$this->inlineScript()
    ->appendFile($this->basePath('module/core/js/select2.min.js'))
    ->appendFile($this->basePath('module/user/settings/js/edit-profile.js'))
;
$addressForm = $this->addressForm;
$addressForm->prepare();
?>
<?php echo $this->breadcrumbs; ?>
<div class="row">
    <div class="col-sm-3">
        <?php echo $this->sidebar; ?>
    </div>
    <div class="col-sm-9">
        <h2 class="head__subtitle">
            <?php echo $this->translate('Address'); ?>
        </h2>
        <div class="row address__settings m-t20">
            <div class="col-xs-12">
                <?php echo $this->form()->openTag($addressForm); ?>
                <div class="b-Bottom">
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Phone number'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('phone')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('phone')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Zip Code'); ?>
                            </p>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group <?php echo $addressForm->get('zip')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('zip')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Country'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('country')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('country')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultCountry" value="<?php echo $element->getValue(); ?>"/>
                        <?php echo $this->formElement($addressForm->get('countryLabel')); ?>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('State'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('state')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('state')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultState" value="<?php echo $element->getValue(); ?>"/>
                        <?php echo $this->formElement($addressForm->get('stateLabel')); ?>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('City'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('city')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('city')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultCity" value="<?php echo $element->getValue(); ?>"/>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Street Address'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('street')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('street')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 text-right m-b20">
                            <?php echo $this->formSubmit($addressForm
                                ->get('submit')
                                ->setAttributes([
                                    'class' => 'btn__default',
                                    'value' => $this->translate('Edit'),
                                ]));?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>