<?php
$this->inlineScript()
    ->appendFile($this->basePath('module/core/js/select2.min.js'))
    ->appendFile($this->basePath('module/user/settings/js/edit-profile.js'))
;
$userForm = $this->userForm;
$userForm->prepare();
$addressForm = $this->addressForm;
$addressForm->prepare();
?>
<?php echo $this->breadcrumbs; ?>
<div class="row">
    <div class="col-sm-3">
        <?php echo $this->sidebar; ?>
    </div>
    <div class="col-sm-9">
        <h2 class="head__title">
            <?php echo $this->translate('Settings'); ?>
        </h2>
        <h3 class="head__subtitle">
            <?php echo $this->translate('Profile'); ?>
        </h3>
        <?php echo $this->form()->openTag($userForm); ?>
            <div class="row m-t20">
                <div class="col-sm-4">
                    <p class="form-label p-t7">
                        <?php echo $this->translate('First name'); ?>
                    </p>
                </div>
                <div class="col-sm-8">
                    <div class="form-group <?php echo $userForm->get('firstName')->getMessages() ? 'has-error' : ''; ?>">
                        <?php $element = $userForm
                            ->get('firstName')
                            ->setAttributes([
                                'class' => 'form-control',
                            ]); ?>
                        <?php echo $this->formInput($element); ?>
                        <?php echo $this->formElementErrors()->render($element); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <p class="form-label p-t7">
                        <?php echo $this->translate('Last name'); ?>
                    </p>
                </div>
                <div class="col-sm-8">
                    <div class="form-group <?php echo $userForm->get('lastName')->getMessages() ? 'has-error' : '';?>">
                        <?php $element = $userForm
                            ->get('lastName')
                            ->setAttributes([
                                'class' => 'form-control',
                            ]); ?>
                        <?php echo $this->formInput($element); ?>
                        <?php echo $this->formElementErrors()->render($element); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <p class="form-label p-t7">
                        <?php echo $this->translate('Email'); ?>
                    </p>
                </div>
                <div class="col-sm-8">
                    <div class="form-group">
                        <input type="text" class="form-control" value="<?php echo $userForm->get('email')->getValue(); ?>" disabled="disabled">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <p class="form-label p-t7">
                        <?php echo $this->translate('Phone number'); ?>
                    </p>
                </div>
                <div class="col-sm-5">
                    <div class="form-group <?php echo $userForm->get('phone')->getMessages() ? 'has-error' : '';?>">
                        <?php $element = $userForm
                            ->get('phone')
                            ->setAttributes([
                                'class' => 'form-control',
                            ]); ?>
                        <?php echo $this->formInput($element); ?>
                        <?php echo $this->formElementErrors()->render($element); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <p class="form-label p-t7">
                        <?php echo $this->translate('PayPal account email'); ?>
                    </p>
                </div>
                <div class="col-sm-5">
                    <div class="form-group <?php echo $userForm->get('paypalEmail')->getMessages() ? 'has-error' : ''; ?>">
                        <?php $element = $userForm
                            ->get('paypalEmail')
                            ->setAttributes([
                                'class' => 'form-control',
                            ]); ?>
                        <?php echo $this->formInput($element); ?>
                        <?php echo $this->formElementErrors()->render($element); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 text-right m-t20">
                    <?php echo $this->formSubmit($userForm
                        ->get('submit')
                        ->setAttributes([
                            'class' => 'btn__default',
                            'value' => $this->translate('Save'),
                        ]));?>
                </div>
            </div>
        <?php echo $this->form()->closeTag() ?>
        <h3 class="head__subtitle">
            <?php echo $this->translate('Address'); ?>
        </h3>
        <div class="row">
            <div class="col-xs-12">

                <?php foreach ($this->zfcUserIdentity()->getAddresses() as $address) : ?>
                    <div class="address">
                        <div class="row">
                            <div class="col-sm-6">
                                <p class="text-lighten">
                                    <?php echo $this->zfcUserIdentity()->getFullName(); ?>
                                </p>
                                <p class="text-page">
                                    <?php echo $address->getPhone(); ?>
                                </p>
                                <p class="text-page">
                                    <?php echo $address->getStreet(); ?>
                                </p>
                                <p class="text-page">
                                    <?php echo $address->getCity() . ', ' . $address->getStateLabel(); ?>
                                </p>
                                <p class="text-page">
                                    <?php echo $address->getCountryLabel(); ?>
                                </p>
                            </div>
                            <div class="col-sm-6 sm-right">
                                <a href="<?php echo $this->url('user_account_settings', ['action' => 'edit-address', 'id' => $address->getId()])?>" class="btn__edit">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                <a href="<?php echo $this->url('user_account_settings', ['action' => 'delete-address', 'id' => $address->getId()])?>" class="btn__trash">
                                    <i class="fa fa-trash"></i>
                                </a>
                                <?php if ($address->getIsDefault()) : ?>
                                    <button class="btn__default m-t40">
                                        <i class="fa fa-check-circle"></i>
                                        <?php echo $this->translate('Default address'); ?>
                                    </button>
                                <?php else : ?>
                                    <a href="<?php echo $this->url('user_account_settings', ['action' => 'set-default-address', 'id' => $address->getId()])?>" class="btn btn__primary m-t40">
                                        <?php echo $this->translate('Use this address'); ?>
                                    </a>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="row address__settings m-t20 <?php echo $addressForm->hasValidated() && !$addressForm->isValid() ? '' : 'is-hidden'; ?>">
            <div class="col-xs-12">
                <?php echo $this->form()->openTag($addressForm); ?>
                <div class="b-Bottom">
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Phone number'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('phone')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('phone')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Zip Code'); ?>
                            </p>
                        </div>
                        <div class="col-sm-5">
                            <div class="form-group <?php echo $addressForm->get('zip')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('zip')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Country'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('country')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('country')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultCountry" value="<?php echo $element->getValue(); ?>"/>
                        <?php echo $this->formElement($addressForm->get('countryLabel')); ?>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('State'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('state')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('state')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultState" value="<?php echo $element->getValue(); ?>"/>
                        <?php echo $this->formElement($addressForm->get('stateLabel')); ?>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('City'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('city')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('city')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formElement($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                        <input type="hidden" name="defaultCity" value="<?php echo $element->getValue(); ?>"/>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Street Address'); ?>
                            </p>
                        </div>
                        <div class="col-sm-8">
                            <div class="form-group <?php echo $addressForm->get('street')->getMessages() ? 'has-error' : '';?>">
                                <?php $element = $addressForm
                                    ->get('street')
                                    ->setAttributes([
                                        'class' => 'form-control',
                                    ]); ?>
                                <?php echo $this->formInput($element); ?>
                                <?php echo $this->formElementErrors()->render($element); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 text-right">
                            <button class="btn__primary m-r5" data-address>
                                <?php echo $this->translate('Cancel'); ?>
                            </button>
                            <?php echo $this->formSubmit($addressForm
                                ->get('submit')
                                ->setAttributes([
                                    'class' => 'btn__default',
                                    'value' => $this->translate('Save'),
                                ])); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
        <div class="row <?php echo $addressForm->hasValidated() && !$addressForm->isValid() ? 'is-hidden' : ''; ?>">
            <div class="col-xs-12 m-tb20">
                <a href="" class="link__page-16 show__address" data-address>
                    + <?php echo $this->translate('Add new address'); ?>
                </a>
            </div>
        </div>
        <h3 class="head__subtitle">
            <?php echo $this->translate('Password'); ?>
        </h3>
        <div class="row m-t20">
            <div class="col-sm-4">
                <div class="form-group">
                    <input type="text" class="form-control" value="******" disabled="disabled">
                </div>
            </div>
            <div class="col-sm-5">
                <a href="<?php echo $this->url('user_account_settings', ['action' => 'reset-password'])?>" class="link__page-16">
                    <i class="fa fa-rotate-left m-r5"></i> <?php echo $this->translate('Change password'); ?>
                </a>
            </div>
        </div>
    </div>
</div>