<?php
$form = $this->form;
$form->prepare();
?>
<?php echo $this->breadcrumbs; ?>
<div class="row">
    <div class="col-sm-3">
        <?php echo $this->sidebar; ?>
    </div>
    <div class="col-sm-9">
        <h2 class="head__subtitle">
            <?php echo $this->translate('Reset Password'); ?>
        </h2>
        <div class="row address__settings m-t20">
            <div class="col-xs-12">
                <?php echo $this->form()->openTag($form); ?>
                <div class="b-Bottom">
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Old password'); ?>
                            </p>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group <?php echo $form->get('oldPassword')->getMessages() ? 'has-error' : '';?>">
                                <?php echo $this->formInput($form->get('oldPassword')->setAttributes([
                                    'class' => 'form-control',
                                ]));
                                ?>
                                <?php echo $this->formElementErrors()->render($form->get('oldPassword')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('New password'); ?>
                            </p>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group <?php echo $form->get('password')->getMessages() ? 'has-error' : '';?>">
                                <?php echo $this->formInput($form->get('password')->setAttributes([
                                    'class' => 'form-control',
                                ]));
                                ?>
                                <?php echo $this->formElementErrors()->render($form->get('password')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="form-label p-t7">
                                <?php echo $this->translate('Confirm password'); ?>
                            </p>
                        </div>
                        <div class="col-sm-4">
                            <div class="form-group <?php echo $form->get('passwordConfirm')->getMessages() ? 'has-error' : '';?>">
                                <?php echo $this->formInput($form->get('passwordConfirm')->setAttributes([
                                    'class' => 'form-control',
                                ]));
                                ?>
                                <?php echo $this->formElementErrors()->render($form->get('passwordConfirm')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-12 text-right m-b20">
                            <?php echo $this->formButton($form->get('submit')->setAttributes([
                                'class' => 'btn__default',
                            ])->setOptions([
                                'label' => 'Save'
                            ])); ?>
                        </div>
                    </div>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>