<?php
/** @var \Core\Entity\User [] $teachers*/
$teachers = $this->teachers;
?>
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->translate('First name'); ?></th>
            <th><?php echo $this->translate('Last name'); ?></th>
            <th><?php echo $this->translate('Email'); ?></th>
            <th><?php echo $this->translate('Phone'); ?></th>
            <th><?php echo $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($teachers as $key => $teacher) : ?>
            <tr>
                <td scope="row"><?php echo $key + 1 ; ?></td>
                <td><?php echo $teacher->getFirstName(); ?></td>
                <td><?php echo $teacher->getLastName(); ?></td>
                <td><?php echo $teacher->getEmail(); ?></td>
                <td><?php echo $teacher->getPhone(); ?></td>
                <td>
                    <a href="<?php echo $this->url('admin_teachers_index', ['action' => 'edit', 'id' => $teacher->getId()]); ?>" class="btn btn-warning btn-xs"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('admin_teachers_index', ['action' => 'delete', 'id' => $teacher->getId()]); ?>" class="btn btn-danger btn-xs"><?php echo $this->translate('Delete'); ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
