<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'superadmin/admins/index' => __DIR__ . '/view/superadmin/admins/index.phtml',
    'superadmin/admins/new'   => __DIR__ . '/view/superadmin/admins/new.phtml',
    'superadmin/admins/edit'  => __DIR__ . '/view/superadmin/admins/edit.phtml',
    'superadmin/index/index'  => __DIR__ . '/view/superadmin/index/index.phtml',
);
