<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'superadmin/admin/index' => __DIR__ . '/view/superadmin/admin/index.phtml',
    'superadmin/admin/new'   => __DIR__ . '/view/superadmin/admin/new.phtml',
    'superadmin/admin/edit'  => __DIR__ . '/view/superadmin/admin/edit.phtml',
    'superadmin/index/index' => __DIR__ . '/view/superadmin/index/index.phtml',
);
