<?php foreach ($this->vars()->getArrayCopy() as $design) : ?>
    <div class="col-sm-6 col-md-4">
        <a href="" class="profile__design__link">
            <div class="profile__design">
                <?php if ($design->getStatus() == \Core\Entity\Design::STATUS_ACTIVE) : ?>
                <a href="<?php echo $this->url('user_account_designs', ['action' => 'edit', 'id' => $design->getId()]); ?>" class="profile__design__remove">
                    <i class="fa fa-pencil"></i>
                </a>
                <?php endif; ?>
                <a href="<?php echo $this->url('user_account_designs', ['action' => 'delete', 'id' => $design->getId()]); ?>" class="profile__design__trash">
                    <i class="fa fa-trash"></i>
                </a>
                <img src="<?php echo $design->getImage()->getFile()->getRelativeUrl('preview'); ?>" height="190" class="profile__design__picture">
                <span class="profile__design__price">
                    <?php echo $this->currencySwitcher()->currencyFormat($design->getPrice()); ?>
                </span>
            </div>
        </a>
    </div>
<?php endforeach; ?>