<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partials/mailing/homework'      => __DIR__ . '/view/partials/mailing/homework.phtml',
    'partials/navigation/guest'      => __DIR__ . '/view/partials/navigation/guest.phtml',
    'partials/navigation/superadmin' => __DIR__ . '/view/partials/navigation/superadmin.phtml',
    'partials/navigation/admin'      => __DIR__ . '/view/partials/navigation/admin.phtml',
    'partials/navigation/student'    => __DIR__ . '/view/partials/navigation/student.phtml',
);
