<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'partials/navigation/guest'      => __DIR__ . '/view/partials/navigation/guest.phtml',
    'partials/navigation/superadmin' => __DIR__ . '/view/partials/navigation/superadmin.phtml',
);
