<tr>
    <td data-th="<?php echo $this->translate('Campaign name'); ?>:">
        <?php echo $campaign->getTitle(); ?>
    </td>
    <td data-th="<?php echo $this->translate('Estimated profit'); ?>:">
<!--        --><?php //echo $campaign->getEarn(); ?>
        profit
    </td>
    <td data-th="<?php echo $this->translate('Items'); ?>:">
        <?php echo $campaign->getCount(); ?>
    </td>
    <td data-th="<?php echo $this->translate('Sold'); ?>:">
<!--        --><?php //echo $campaign->getCount(); ?>
        Sold
    </td>
    <td data-th="<?php echo $this->translate('Date end'); ?>:">
        <?php echo $campaign->getCreatedAt()->format('m/d/Y'); ?>
    </td>
    <td data-th="<?php echo $this->translate('Status'); ?>:">
                        <span class="order__pending">
                            <i class="m-r5 icon-pending"></i>
                            <?php echo $this->translate('Pending'); ?>
                        </span>
        <!--<span class="order__completed">
            <i class="m-r5 icon-complete"></i>
            Completed
        </span>
        <span class="order__cancelled">
            <i class="m-r5 icon-cancelled"></i>
            Cancelled
        </span>-->
    </td>
    <td data-th="Action:">
        <a href="<?php echo $this->url('user_account_campaigns', ['action' => 'view', 'id' => $campaign->getId()]); ?>" class="order__link">
            <?php echo $this->translate('View details'); ?>
        </a>
    </td>
</tr>