<div class="block__upload is-hidden">
    <div class="row">
        <div class="col-sm-6">
            <div class="configurator__body">
                <h3 class="configurator__body__title">
                    Details
                </h3>
                <p class="form-label">
                    Campaign title
                </p>
                <div class="form-group">
                    <input type="text" class="form-control">
                </div>
                <p class="form-label">
                    Description
                </p>
                <div class="form-group">
                    <textarea id="description" class="form-control" rows="10"></textarea>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <a href="" class="link__page-16" >
                            <i class="icon-circle-plus m-r5"></i> Tag your company
                        </a>
                    </div>
                </div>
                <p class="form-label m-t20">
                    Duration
                </p>
                <div class="form-group">
                    <select type="text" class="form-control">
                        <option value="">7 Days (Ending Wednesday, Augest 5, 2015)</option>
                        <option value="">Ending Wednesday</option>
                    </select>
                    <p class="title_text p-t5">
                        <small>
                            US orders will arrive 10-14 days after the end of the campaign.
                            <a href="" class="link__page-12" >
                                Learn more
                            </a>
                        </small>
                    </p>
                </div>
                <p class="form-label">
                    URL
                </p>
                <div class="input-group">
                    <span class="input-group-addon">justshirt.com/</span>
                    <input type="text" class="form-control" placeholder="Username">
                </div>
                <h3 class="configurator__body__title">
                    Shipping options
                </h3>
                <label class="cb-checkbox w-100">
                    <input type="checkbox">
                    Allow buyers to pick up their orders from you
                </label>
                <p class="title_text">
                    <small>
                        Please note pick-up is currently only available to US Addresses.
                    </small>
                </p>
                <p class="form-label m-t20">
                    Where/when will buyers be able to pick up their shirts?
                </p>
                <div class="form-group">
                    <textarea rows="5" class="form-control"></textarea>
                    <p class="title_text p-t5">
                        <small>
                            Buyers will see these instructions when choosing between shipping/pick-up
                        </small>
                    </p>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <p class="form-label">
                            First name
                        </p>
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <p class="form-label">
                            Last name
                        </p>
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8">
                        <p class="form-label">
                            Contry
                        </p>
                        <div class="form-group">
                            <select type="text" class="form-control">
                                <option value="">USA</option>
                                <option value="">Belarus</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <p class="form-label">
                            Zipcode
                        </p>
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <p class="form-label">
                            State
                        </p>
                        <div class="form-group">
                            <select type="text" class="form-control">
                                <option value="">USA</option>
                                <option value="">Belarus</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <p class="form-label">
                            City
                        </p>
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <p class="form-label">
                            Address
                        </p>
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <h3 class="configurator__body__title">
                    Display Options
                </h3>
                <label class="cb-checkbox w-100">
                    <input type="checkbox">
                    Show the back side by default
                </label>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <button class="btn__primary m-r20" data-back="">
                        Back
                    </button>
                    <button class="btn__default">
                        Launch
                    </button>
                </div>
            </div>
        </div>
        <div class="col-sm-6 text-center p-t20">
            <img src="images/configurator/shirt.png" alt="">
            <button class="btn__primary">
                Front
            </button>
            <button class="btn__primary">
                Back
            </button>
        </div>
    </div>
</div>