<div class="is-relative block__upload">
    <ul class="configurator__aside clearfix">
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-shirt"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-cups"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-suspenders"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-cup"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-towel"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-pillo"></i>
            </a>
        </li>
        <li class="configurator__aside__item">
            <a href="" class="configurator__aside__item__link">
                <i class="icon-gray-belts"></i>
            </a>
        </li>
    </ul>
    <div class="configurator__settings">
        <div class="configurator__settings__item active" data-accordeon>
            <h3 class="configurator__settings__title">
                Style & design
            </h3>
            <div class="configurator__settings__item__body" data-accordeon-body>
                <p class="text-lighten">
                    Choose style & design
                </p>
                <div class="form-group">
                    <select class="chosen-select">
                        <option value=""></option>
                        <option value="">Women's Tees</option>
                    </select>
                </div>
                <div class="clearfix">
                    <div class="configurator__settings__filter">
                        <p class="text-lighten">
                            Select size
                        </p>
                        <select class="chosen-select">
                            <option value="">All sizes</option>
                            <option value="">S</option>
                            <option value="">M</option>
                            <option value="">L</option>
                        </select>
                    </div>
                    <div class="configurator__settings__filter">
                        <p class="text-lighten">
                            Print type
                        </p>
                        <select class="chosen-select">
                            <option value="">All</option>
                            <option value="">Trees</option>
                            <option value="">Plants</option>
                        </select>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="configurator__create__settings">
                            <div class="configurator__create__settings__item clearfix" data-popover>
                                <div class="configurator__create__settings__item__content">
                                    <div class="popover popover__left" data-toggle-popover>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__red"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__pink"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__orange"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__green"></div>
                                        </div>
                                    </div>
                                    <i class="icon-long-shirt"></i>
                                    <h3 class="configurator__create__settings__item__title">
                                        Teespring Women’s
                                    </h3>
                                    <p class="configurator__create__settings__item__text">
                                        Premium materials XS - 4XL
                                    </p>
                                </div>
                            </div>
                            <div class="configurator__create__settings__item clearfix" data-popover>
                                <div class="configurator__create__settings__item__content">
                                    <div class="popover popover__left" data-toggle-popover>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__red"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__pink"></div>
                                        </div>
                                    </div>
                                    <i class="icon-middle-shirt"></i>
                                    <h3 class="configurator__create__settings__item__title">
                                        American Apparel Women's Fitted Tee
                                    </h3>
                                    <p class="configurator__create__settings__item__text">
                                        Top of the line S (4) - 2 XL (18-20)
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-xs-12">
                        <div class="configurator__create__settings">
                            <div for="chose-shirt3" class="configurator__create__settings__item clearfix" data-popover>
                                <div class="configurator__create__settings__item__content">
                                    <div class="popover popover__left" data-toggle-popover>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__red"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__pink"></div>
                                        </div>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__orange"></div>
                                        </div>
                                    </div>
                                    <i class="icon-middle-shirt"></i>
                                    <h3 class="configurator__create__settings__item__title">
                                        Canvas Triblend Tee
                                    </h3>
                                    <p class="configurator__create__settings__item__text">
                                        Premium materials S – 2XL
                                    </p>
                                </div>
                            </div>
                            <div for="chose-shirt4" class="configurator__create__settings__item clearfix" data-popover>
                                <div class="configurator__create__settings__item__content">
                                    <div class="popover popover__left" data-toggle-popover>
                                        <div class="popover__block">
                                            <div class="popover__block__color color__red"></div>
                                        </div>
                                    </div>
                                    <i class="icon-small-shirt"></i>
                                    <h3 class="configurator__create__settings__item__title">
                                        Teespring Women’s
                                    </h3>
                                    <p class="configurator__create__settings__item__text">
                                        Premium materials XS - 4XL
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="configurator__settings__item" data-accordeon>
            <h3 class="configurator__settings__title" >
                Text
            </h3>
            <div class="configurator__settings__item__body" data-accordeon-body>
                <p class="text-lighten">
                    Enter text below
                </p>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group">
                            <input type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <p class="text-lighten">
                    Choose a font
                </p>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="form-group">
                            <select class="chosen-select">
                                <option value="">Comic Sans</option>
                                <option value="">Ubuntu</option>
                                <option value="">Lato</option>
                                <option value="">Open Sans</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class="input-group color">
                                <input type="text" value="" class="form-control" data-color />
								<span class="input-group-addon">
									<span class="input-group-addon_content">
										<i></i>
									</span>
								</span>
                            </div>
                        </div>
                    </div>
                </div>
                <p class="text-lighten">
                    Add on outline
                </p>
                <div class="row">
                    <div class="col-xs-8">
                        <div class="form-group">
                            <select class="chosen-select">
                                <option value="">No outline</option>
                                <option value="">Ubuntu</option>
                                <option value="">Lato</option>
                                <option value="">Open Sans</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-xs-4">
                        <div class="form-group">
                            <div class="input-group color">
                                <input type="text" value="" class="form-control" data-color />
								<span class="input-group-addon">
									<span class="input-group-addon_content">
										<i></i>
									</span>
								</span>
                            </div>
                        </div>
                    </div>
                </div>
                <label class="cb-checkbox cb-gray m-t15">
                    <input type="checkbox">
                    Snap to center
                </label>
                <div class="row">
                    <div class="col-xs-12 p-tb10">
                        <button class="btn-change-element">
                            <i class="icon-double"></i>
                        </button>
                        <button class="btn-change-element">
                            <i class="icon-center"></i>
                        </button>
                        <button class="btn-change-element">
                            <i class="icon-front"></i>
                        </button>
                        <button class="btn-change-element">
                            <i class="icon-horizontal"></i>
                        </button>
                        <button class="btn-change-element">
                            <i class="icon-vertical"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        <div class="configurator__settings__item" data-accordeon>
            <h3 class="configurator__settings__title">
                Art
            </h3>
            <div class="configurator__settings__item__body" data-accordeon-body>
                <div class="p-tb110 text-center">
                    <button class="btn-browse">
                        Browse Artwork
                    </button>
                    <div class="block__or">
                        <span class="block__or__text">or</span>
                    </div>
                    <button class="btn-browse">
                        Upload your own
                    </button>
                </div>
            </div>
        </div>
        <div class="row m-tb20">
            <div class="col-sm-6">
                <p class="cost__text">Base cost @ 50 shirts</p>
                <p class="cost">$7.14</p>
            </div>
            <div class="col-sm-6">
                <button class="btn__accept" data-forward>
                    Continue
                </button>
            </div>
        </div>
    </div>
    <div class="configurator__content">
        <img class="configurator__content__picture" src="images/configurator/shirt.png" alt="">
        <button class="btn__primary">
            Front
        </button>
        <button class="btn__primary">
            Back
        </button>
    </div>
</div>