<?php
/** @var \Core\Entity\User [] $administrators */
$administrators = $this->administrators;
?>
<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->translate('First name'); ?></th>
            <th><?php echo $this->translate('Last name'); ?></th>
            <th><?php echo $this->translate('Email'); ?></th>
            <th><?php echo $this->translate('Actions'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($administrators as $key => $administrator) : ?>
            <tr>
                <td scope="row"><?php echo $key + 1 ; ?></td>
                <td><?php echo $administrator->getFirstName(); ?></td>
                <td><?php echo $administrator->getLastName(); ?></td>
                <td><?php echo $administrator->getEmail(); ?></td>
                <td>
                    <a href="<?php echo $this->url('superadmin_admin_index', ['action' => 'edit', 'id' => $administrator->getId()]); ?>" class="btn btn-warning btn-xs"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('superadmin_admin_index', ['action' => 'delete', 'id' => $administrator->getId()]); ?>" class="btn btn-danger btn-xs"><?php echo $this->translate('Delete'); ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
