<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <form class="form-horizontal">
            <h2><?php echo $this->translate('Login to your account'); ?></h2>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Email">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Password">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Sign in</button>
            </div>
        </form>
    </div>
</div>