<?php
$form = $this->loginForm;
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?php echo $this->form()->openTag($form); ?>
            <h2><?php echo $this->translate('Login to your account'); ?></h2>
            <div class="form-group">
                <?php echo $this->formElement($form->get('identity')->setAttributes([
                    'class' => 'form-control',
                    'placeholder' => 'Email',
                ])); ?>
                <?php echo $this->formElementErrors()->render($form->get('identity')); ?>
            </div>
            <div class="form-group">
                <?php echo $this->formElement($form->get('credential')->setAttributes([
                    'class' => 'form-control',
                    'placeholder' => 'Password',
                ])); ?>
                <?php echo $this->formElementErrors()->render($form->get('credential')); ?>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-default">Sign in</button>
            </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>