<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="<?php echo $this->url('admin_index_index', ['action' => 'index']); ?>" class="navbar-brand"><?php echo $this->translate('Admin'); ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('admin_teachers_index', ['action' => 'index']); ?>"><?php echo $this->translate('Teachers'); ?></a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><?php echo $this->translate('Logout'); ?></a></li>
            </ul>
        </div>
    </div>
</nav>