<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="<?php echo $this->url('home'); ?>" class="navbar-brand"><?php echo $this->translate('Guest'); ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?php echo $this->url('zfcuser/login'); ?>"><?php echo $this->translate('Login'); ?></a></li>
            </ul>
        </div>
    </div>
</nav>