<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="<?php echo $this->url('superadmin_index_index', ['action' => 'index']); ?>" class="navbar-brand"><?php echo $this->translate('Superadmin'); ?></a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <?php echo $this->translate('Administrators'); ?>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $this->url('superadmin_admin_index', ['action' => 'index']); ?>"><?php echo $this->translate('List'); ?></a></li>
                        <li class="divider" role="separator"></li>
                        <li><a href="<?php echo $this->url('superadmin_admin_index', ['action' => 'new']); ?>"><?php echo $this->translate('New'); ?></a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url('zfcuser/logout'); ?>"><?php echo $this->translate('Logout'); ?></a></li>
            </ul>
        </div>
    </div>
</nav>