<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'teacher/index/index'         => __DIR__ . '/view/teacher/index/index.phtml',
    'teacher/students/index'      => __DIR__ . '/view/teacher/students/index.phtml',
    'teacher/students/new'        => __DIR__ . '/view/teacher/students/new.phtml',
    'teacher/students/edit'       => __DIR__ . '/view/teacher/students/edit.phtml',
    'teacher/groups/index'        => __DIR__ . '/view/teacher/groups/index.phtml',
    'teacher/groups/new'          => __DIR__ . '/view/teacher/groups/new.phtml',
    'teacher/groups/view'         => __DIR__ . '/view/teacher/groups/view.phtml',
    'teacher/groups/add-homework' => __DIR__ . '/view/teacher/groups/add-homework.phtml',
    'teacher/groups/edit'         => __DIR__ . '/view/teacher/groups/edit.phtml',
);
