<tr>
    <td data-th="<?php echo $this->translate('Order'); ?> #:">
        #<?php echo $order->getId(); ?>
    </td>
    <td data-th="<?php echo $this->translate('Order date'); ?>:">
        <?php echo $order->getCreatedAt()->format('m/d/Y'); ?>
    </td>
    <td data-th="<?php echo $this->translate('Status'); ?>:">
                        <span class="order__pending">
                            <i class="m-r5 icon-pending"></i>
                            <?php echo $this->translate('Pending'); ?>
                        </span>
        <!--<span class="order__completed">
            <i class="m-r5 icon-complete"></i>
            Completed
        </span>
        <span class="order__cancelled">
            <i class="m-r5 icon-cancelled"></i>
            Cancelled
        </span>-->
    </td>
    <td data-th="Action:">
        <a href="<?php echo $this->url('user_account_purchases', ['action' => 'view', 'id' => $order->getId()]); ?>" class="order__link">
            <?php echo $this->translate('View details'); ?>
        </a>
    </td>
</tr>