<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'admin/teachers/index' => __DIR__ . '/view/admin/teachers/index.phtml',
    'admin/teachers/new'   => __DIR__ . '/view/admin/teachers/new.phtml',
    'admin/teachers/edit'  => __DIR__ . '/view/admin/teachers/edit.phtml',
    'admin/index/index'    => __DIR__ . '/view/admin/index/index.phtml',
);
