<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>
<div class="row">
    <div class="col-md-offset-2 col-md-8">
        <?php echo $this->form()->openTag($form); ?>
        <h2><?php echo $this->translate('Set homework'); ?></h2>
        <div class="form-group">
            <?php echo $this->formElement($form->get('content')->setAttributes([
                'class' => 'form-control',
                'placeholder' => 'Content',
                'rows' => 15,
            ])); ?>
            <?php echo $this->formElementErrors()->render($form->get('content')); ?>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-default"><?php echo $this->translate('Save'); ?></button>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>