<?php
/** @var \Core\Entity\Group $group*/
$group = $this->group;
/** @var \Core\Entity\Homework $homework*/
$homework = $this->homework;
?>
<div class="row">
    <div class="col-md-6">
        <h3><?php echo sprintf($this->translate('Group "%s"'), $group->getTitle()); ?></h3>
        <p><?php echo $this->translate(ucfirst($group->getWeekday())) . ', ' . $group->getTeacherName(); ?></p>
    </div>
    <div class="col-md-6">
        <a href="<?php echo $this->url('admin_groups_index', ['action' => 'add-homework', 'id' => $group->getId()]); ?>" class="btn btn-info pull-right"><?php echo $this->translate('Set homework'); ?></a>
    </div>
</div>
<table class="table table-striped">
    <thead>
    <tr>
        <th>#</th>
        <th><?php echo $this->translate('Name'); ?></th>
        <th><?php echo $this->translate('Email'); ?></th>
        <th><?php echo $this->translate('Contact name'); ?></th>
        <th><?php echo $this->translate('Phone'); ?></th>
        <th><?php echo $this->translate('Actions'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($group->getStudents() as $key => $student) : ?>
        <tr>
            <td scope="row"><?php echo $key + 1 ; ?></td>
            <td><?php echo $student->getService()->getFirstLastName(); ?></td>
            <td><?php echo $student->getEmail(); ?></td>
            <td><?php echo $student->getContactName(); ?></td>
            <td><?php echo $student->getPhone(); ?></td>
            <td>
                <a href="<?php echo $this->url('admin_students_index', ['action' => 'edit', 'id' => $student->getId()]); ?>" class="btn btn-warning btn-xs"><?php echo $this->translate('Edit'); ?></a>
                <a href="<?php echo $this->url('admin_students_index', ['action' => 'delete', 'id' => $student->getId()]); ?>" class="btn btn-danger btn-xs"><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<div class="row">
    <div class="col-md-12">
        <h4><?php echo $this->translate('Current homework'); ?></h4>
        <?php if ($homework) : ?>
            <?php echo nl2br($homework->getContent()); ?>
        <?php else : ?>
            <?php echo $this->translate('No homework'); ?>
        <?php endif; ?>
    </div>
</div>