<div class="total__block catalog" data-item_id="<?php echo $product->getId(); ?>">
    <p class="total__block__text">
        <span class="remove__checkout pull-md-left">x</span>&nbsp;<?php echo sprintf($this->translate('%s has been deleted'), $product->getName()) ; ?>.
        <a href="javascript:void(0);" class="restore pull-md-right"><?php echo $this->translate('Restore'); ?></a>
    </p>
    <div class="loading__block col-xs-12 is-hidden">
        <i class="fa fa-spinner fa-pulse"></i>
    </div>
</div>