<?php
/** @var \Core\Entity\Group [] $groups*/
$groups = $this->groups;
?>
<div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th><?php echo $this->translate('Title'); ?></th>
            <th><?php echo $this->translate('Weekday'); ?></th>
            <th><?php echo $this->translate('Teacher'); ?></th>
            <th><?php echo $this->translate('Students count'); ?></th>
            <th><?php echo $this->translate('Actions'); ?></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($groups as $key => $group) : ?>
            <tr>
                <td scope="row"><?php echo $key + 1 ; ?></td>
                <td><a href="<?php echo $this->url('teacher_groups_index', ['action' => 'view', 'id' => $group->getId()]); ?>"><?php echo $group->getTitle(); ?></a></td>
                <td><?php echo $this->translate(ucfirst($group->getWeekday())); ?></td>
                <td><?php echo $group->getTeacher()->getService()->getFirstLastName(); ?></td>
                <td><?php echo $group->getStudents()->count(); ?></td>
                <td>
                    <a href="<?php echo $this->url('teacher_groups_index', ['action' => 'edit', 'id' => $group->getId()]); ?>" class="btn btn-warning btn-xs"><?php echo $this->translate('Edit'); ?></a>
                    <a href="<?php echo $this->url('teacher_groups_index', ['action' => 'delete', 'id' => $group->getId()]); ?>" class="btn btn-danger btn-xs"><?php echo $this->translate('Delete'); ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>