<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Teaching '. $this->translate('Education Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ; ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/module/core/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('module/core/css/teaching.css'))
                        ->prependStylesheet($this->basePath('module/core/css/bootstrap.min.css'))
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('module/core/js/bootstrap.min.js'))
            ->prependFile($this->basePath('module/core/js/jquery.min.js'))
            ->prependFile($this->basePath('module/core/js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('module/core/js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
