<?php foreach ($paginator as $payment) : ?>
    <tr>
    	<td data-th="<?php echo $this->translate('Payment'); ?> #:">
        #<?php echo $payment->getId(); ?>
    	</td>
    <td data-th="<?php echo $this->translate('Create'); ?>:">
        <?php echo $payment->getCreatedAt()->format('m/d/Y'); ?>
    </td>
    <td data-th="<?php echo $this->translate('Amount'); ?>:">
        <?php echo $this->currencySwitcher()->currencyFormat($payment->getAmount()); ?>
    </td>
    <td data-th="<?php echo $this->translate('Message'); ?>:">
        <?php echo $payment->getMessage(); ?>
    </td>
    <td data-th="<?php echo $this->translate('Status'); ?>:">
        <span class="order__pending">
            <i class="m-r5 icon-pending"></i>
            <?php echo $this->translate('Pending'); ?>
        </span>
    </td>
</tr>
<?php endforeach; ?>