<tr>
    <td data-th="<?php echo $this->translate('Item'); ?> #:">
        #<?php echo $item->getId(); ?>
    </td>
    <td data-th="<?php echo $this->translate('Order date'); ?>:">
        <?php echo $item->getCreatedAt()->format('m/d/Y'); ?>
    </td>
    <td data-th="<?php echo $this->translate('Status'); ?>:">
        <?php if ($item->getStatus() == \Core\Entity\OrderItem::STATUS_COMPLETED) : ?>
            <span class="order__completed">
                <i class="m-r5 icon-complete"></i>
                <?php echo $this->translate('Completed'); ?>
            </span>
        <?php elseif ($item->getStatus() == \Core\Entity\OrderItem::STATUS_PENDING) : ?>
            <span class="order__pending">
                <i class="m-r5 icon-pending"></i>
                <?php echo $this->translate('Pending'); ?>
            </span>
        <?php elseif ($item->getStatus() == \Core\Entity\OrderItem::STATUS_CANCELLED) : ?>
            <span class="order__cancelled">
                <i class="m-r5 icon-cancelled"></i>
                <?php echo $this->translate('Cancelled'); ?>
            </span>
        <?php endif; ?>
    </td>
    <td data-th="<?php echo $this->translate('Action'); ?>:">
        <a href="<?php echo $this->url('user_account_sales', ['action' => 'view', 'id' => $item->getId()]); ?>" class="order__link">
            <?php echo $this->translate('View details'); ?>
        </a>
    </td>
</tr>