<?php echo $this->breadcrumbs; ?>
<div class="row">
    <div class="col-sm-3">
        <?php echo $this->sidebar; ?>
    </div>
    <div class="col-sm-9">
        <h2 class="head__title">
            <?php echo $this->translate('Sold Item Details'); ?>
        </h2>
        <table class="checkout__products responsive__table">
            <thead>
            <tr>
                <th></th>
                <th><?php echo $this->translate('Product Name'); ?></th>
                <th><?php echo $this->translate('QTY'); ?></th>
                <th><?php echo $this->translate('Total'); ?></th>
                <th><?php echo $this->translate('Status'); ?></th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-th="<?php echo $this->translate('Product Image'); ?>:">
                        <div class="product__preview">
                            <div class="product__preview__picture">
                                <img src="<?php echo $this->imageUrl($orderItem->getProduct()->getImages()->first(), 'preview'); ?>" alt="" class="product__preview__avatar">
                            </div>
                        </div>
                    </td>
                    <td data-th="<?php echo $this->translate('Product Name'); ?>:">
                        <h2 class="checkout__products__title">
                            <?php echo $orderItem->getProduct()->getName(); ?>
                        </h2>
                        <ul class="checkout__products__list">
                            <li class="checkout__products__list__item">
                                <?php echo $orderItem->getProduct()->getType()->getTitle(); ?> Size <span><?php echo $orderItem->getProductSize(); ?></span>
                            </li>
                            <li class="checkout__products__list__item">
                                <?php echo $orderItem->getProduct()->getType()->getTitle(); ?> Color <span><?php echo $orderItem->getProductColor(); ?></span>
                            </li>
                            <li class="checkout__products__list__item">
                                <?php echo $this->translate('Additional Options'); ?> <br>
                                <span><?php echo $orderItem->getProductAdditional(); ?></span>
                            </li>
                        </ul>
                    </td>
                    <td data-th="<?php echo $this->translate('QTY'); ?>:">
                        <?php echo $orderItem->getQuantity(); ?>
                    </td>
                    <td data-th="<?php echo $this->translate('Total'); ?>:">
                        <?php echo $this->currencySwitcher()->currencyFormat($orderItem->getProductAmount() * $orderItem->getQuantity()); ?>
                    </td>
                    <td data-th="<?php echo $this->translate('Status'); ?>:">
                        <?php if ($orderItem->getStatus() == \Core\Entity\OrderItem::STATUS_COMPLETED) : ?>
                            <span class="order__completed">
                            <i class="m-r5 icon-complete"></i>
                                <?php echo $this->translate('Completed'); ?>
                        </span>
                        <?php elseif ($orderItem->getStatus() == \Core\Entity\OrderItem::STATUS_PENDING) : ?>
                            <span class="order__pending">
                            <i class="m-r5 icon-pending"></i>
                                <?php echo $this->translate('Pending'); ?>
                        </span>
                        <?php elseif ($orderItem->getStatus() == \Core\Entity\OrderItem::STATUS_CANCELLED) : ?>
                            <span class="order__cancelled">
                            <i class="m-r5 icon-cancelled"></i>
                                <?php echo $this->translate('Cancelled'); ?>
                        </span>
                        <?php endif; ?>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</div>